version: "3.9"
services:
  postgres:
    image: "postgres"
    container_name: "mtp_jfest_postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
  web:
    build: .
    ports: 
      - "5000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres
      - JWT_SECRET=secret
    links:
      - postgres